const BUTTON_MORE_DECKTOP = 4;
const BUTTON_MORE_TABLET = 3;
const BUTTON_MORE_MOBILE = 2;
const SHORT_MOVIES = 40;

const WIDTH_MOBILE_LARGE = 480;
const WIDTH_MOBILE = 481;
const WIDTH_TABLET_PORTRAIT = 701;
const WIDTH_TABLET_LANDSCAPE = 700;
const WIDTH_DECKTOP = 801;
const WIDTH_DECKTOP_LARGE = 1180;

const COLUMN_X1 = 5;
const COLUMN_X2 = 8;
const COLUMN_X3 = 12;
const COLUMN_X4 = 16;

const EMAIL_REGEX = '[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}$';
const USERNAME_REGEX = '^[^\\s]+[A-Za-zА-Яа-я\\s\\-]{1,30}$';

export {
    COLUMN_X1,
    COLUMN_X2,
    COLUMN_X3,
    COLUMN_X4,
    WIDTH_DECKTOP_LARGE,
    WIDTH_DECKTOP,
    WIDTH_TABLET_LANDSCAPE,
    WIDTH_TABLET_PORTRAIT,
    WIDTH_MOBILE,
    WIDTH_MOBILE_LARGE,
    BUTTON_MORE_DECKTOP,
    BUTTON_MORE_TABLET,
    BUTTON_MORE_MOBILE,
    SHORT_MOVIES,
    EMAIL_REGEX,
    USERNAME_REGEX,
};
